version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/teacher_attendance
      - JWT_SECRET=your_jwt_secret_key
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  mongo-data: